### ISSUE TITLE
KuModel can't find package data

### ISSUE THREAD

**Issue by mdpiper** [permamodel/permamodel#20]
Here's a reproduce case.

1. Clone the permamodel repo.

        git clone https://github.com/permamodel/permamodel.git

1. Change to the permamodel directory and install permamodel. This installs the package data into the **site-packages** directory of the Python distribution.

        cd permamodel
        root=$PWD
        python setup.py install

1. Change to another directory outside of the permamodel repo.

        cd && mkdir -p tmp && cd tmp

1. Run the test script that @wk1984 wrote.

        python $root/permamodel/tests/run_test_BMI_ku_model.py

1. (Optional) Remove permamodel with `pip`:

          pip uninstall permamodel

**Result**: The test script fails with an error message.

        Ku model component: Initializing...
        Error: File ./permamodel/components/Parameters/T_CLAY.nc4 does not exist

**Expected**: The test script should pass.

My hunch (which may be wrong) is that KuModel isn't reading the information from its cfg file. I think it needs to call `initialize_from_config_file()` in **perma_base.py**. However, that method should also be revisited because it has a chunk devoted to FrostNumberModel.

**Comment by wk1984** [comment]
I think the mistake may be in the function "get_param_nc4_filename". I am working on it. The directory in cfg file looks like a bit confused.

**Comment by mdpiper** [comment]
I think step 4 above should be
```
python -m permamodel.tests.run_test_BMI_ku_model
```
