### ISSUE TITLE
Test on MacOS

### ISSUE THREAD

**Issue by mdpiper** [permamodel/permamodel#22]
We use Travis CI for continuous integration testing. We currently only test on Linux. We should test on MacOS, as well.

Note that this will require significant revision of the **.travis.yml** file. And likely the use of miniconda-based Python instead of the default Python on Travis.

**Comment by sc0tts** [comment]
This sounds good to me.  

Mark, I assume you'll take the lead on updating the .travis.yml file?

**Comment by sc0tts** [comment]
After this is accomplished, do we also want to add a Windows check?  I have a Windows machine I could use to verify....

**Comment by mdpiper** [comment]
For Windows, we'll use [Appveyor](https://ci.appveyor.com), and model our setup on what @mcflugen did with the [csdms/standard_names](https://github.com/csdms/standard_names) repo.

**Comment by mdpiper** [comment]
Fixed with the move to GitHub Actions in #73.
