### ISSUE TITLE
Old branches

### ISSUE THREAD

**Issue by sc0tts** [permamodel/permamodel#25]
While creating my latest pull request, I noticed that we have a couple of old branches of the code on the repository.  

wk1984-patch-1 is quite old (7 months!) and can probably be deleted.

bmi_ku_check is about a month old.  I'm assuming the changes in that repo have been merged already?

**Comment by wk1984** [comment]
I cleared those old branches.

**Comment by sc0tts** [comment]
Great!  Okay, I'm going to close this issue within the hour....

**Comment by sc0tts** [comment]
Issue closed because all inactive branches have been deleted.
