### ISSUE TITLE
 Ku-2D case

### ISSUE THREAD

**Issue by wk1984** [permamodel/permamodel#31]
Hi @mdpiper and @sc0tts, I added a 2D case of Ku model. 

1) sample dataset was put in folder "Ku_2D_Input". I just used a coarse resolution of 0.5 deg.
2) configure file is "Ku_method_2D.cfg"
3) a notebook file is "Ku_2D.ipynb", which provides a basic visualization of simulated results.
4) I also added a script for creating input files from ERA raw data ("pre_process/Raw_ERA_Dataset.nc") by using CDO (Climate Data Operator): "pre_process/CDO_cmds.sh".
5) assume latitude and longitude were provided in the netcdf file, and named exactly by "latitude" and "longitude", respectively.

Please take some time to review.

Best,
Kang

**Comment by mdpiper** [comment]
Thanks, Kang! I'll review your code. For future development, I'll show you more about submitting a pull request -- it's a convenient way for team members to review code in GitHub.

**Comment by mdpiper** [comment]
This has been moved to PR #35. Let's leave this issue open until that PR is accepted.

**Comment by mdpiper** [comment]
PR #35 has been accepted.
