### ISSUE TITLE
testing Ku model in WMT with timeseries

### ISSUE THREAD

**Issue by iovereem** [permamodel/permamodel#37]
WMT reports an error when uploading time series files for a simulation. 
I uploaded a 1961-2015 text file for respectively: MAAT, Amplitude of Temperature and Snow Thickness. 
Set it to be a 55 year simulation. 

Files are UnixLF and Unicode UFI8 from Textwrangler. I attached them for testin, but it looks to be something in the BMI arguments?

[MAATBarrow1961-2015.txt](https://github.com/permamodel/permamodel/files/984879/MAATBarrow1961-2015.txt)
[SDBarrow1961-2015.txt](https://github.com/permamodel/permamodel/files/984880/SDBarrow1961-2015.txt)
[TAMPBarrow1961-2015.txt](https://github.com/permamodel/permamodel/files/984881/TAMPBarrow1961-2015.txt)

Here is the traceback error reporting: 

{
  "status": "error", 
  "model_id": 21, 
  "updated": "2017-05-08 15:08:38.909488", 
  "name": "KuModel_Barrow55years", 
  "created": "2017-05-08 15:08:26.642192", 
  "owner": "irina.overeem@gmail.com", 
  "message": "Traceback (most recent call last):\n  File \"/home/csdms/wmt/permafrost/opt/wmt-exe/wmtexe/cmd/slave.py\", line 53, in main\n    _ = slave.start_task(args.id, dir=args.exec_dir, env=env)\n  File \"/home/csdms/wmt/permafrost/opt/wmt-exe/wmtexe/slave.py\", line 78, in start_task\n    return self._tasks[id].execute()\n  File \"/home/csdms/wmt/permafrost/opt/wmt-exe/wmtexe/task.py\", line 652, in execute\n    self.run()\n  File \"/home/csdms/wmt/permafrost/opt/wmt-exe/wmtexe/task.py\", line 786, in run\n    model.go(filename='model.yaml')\n  File \"/home/csdms/wmt/permafrost/opt/pymt/pymt/component/model.py\", line 96, in go\n    self._components[self.driver].go(self.duration)\n  File \"/home/csdms/wmt/permafrost/opt/pymt/pymt/component/component.py\", line 243, in go\n    self.initialize()\n  File \"/home/csdms/wmt/permafrost/opt/pymt/pymt/component/component.py\", line 256, in initialize\n    self._events.initialize()\n  File \"/home/csdms/wmt/permafrost/opt/pymt/pymt/events/manager.py\", line 114, in initialize\n    event.initialize()\n  File \"/home/csdms/wmt/permafrost/opt/pymt/pymt/events/port.py\", line 59, in initialize\n    self._port.initialize(*self._init_args)\n  File \"/home/csdms/wmt/permafrost/opt/pymt/pymt/framework/bmi_bridge.py\", line 292, in initialize\n    return bmi_call(self.bmi.initialize, *args)\n  File \"/home/csdms/wmt/permafrost/opt/pymt/pymt/framework/bmi_bridge.py\", line 49, in bmi_call\n    rtn = func(*args)\n_Exception\n", 
  "stage_dir": "/data/web/htdocs/wmt/api/permafrost/files/downloads/6b082e29-235d-4043-a260-b3e90da9ce60", 
  "id": 28, 
  "uuid": "6b082e29-235d-4043-a260-b3e90da9ce60"
}

**Comment by mdpiper** [comment]
Within the Topoflow framework, we expect one value per time step to be read from a time series file. This isn't working right now in KuModel. @wk1984, if you have a moment to visit me, I can demonstrate what's happening and suggest a path to a solution.

**Comment by iovereem** [comment]
Just a quick response to MP's email yesterday. I tested Ku model with time series through wmt_permafrost project this morning. 

It still gives an error and the traceback looks as follows: 
{
  "status": "error", 
  "model_id": 27, 
  "updated": "2017-05-13 07:46:21.957156", 
  "name": "KuModeltestTS", 
  "created": "2017-05-13 07:46:03.505780", 
  "owner": "irina.overeem@gmail.com", 
  "message": "Traceback (most recent call last):\n  File \"/home/csdms/wmt/permafrost/opt/wmt-exe/wmtexe/cmd/slave.py\", line 53, in main\n    _ = slave.start_task(args.id, dir=args.exec_dir, env=env)\n  File \"/home/csdms/wmt/permafrost/opt/wmt-exe/wmtexe/slave.py\", line 78, in start_task\n    return self._tasks[id].execute()\n  File \"/home/csdms/wmt/permafrost/opt/wmt-exe/wmtexe/task.py\", line 652, in execute\n    self.run()\n  File \"/home/csdms/wmt/permafrost/opt/wmt-exe/wmtexe/task.py\", line 786, in run\n    model.go(filename='model.yaml')\n  File \"/home/csdms/wmt/permafrost/opt/pymt/pymt/component/model.py\", line 96, in go\n    self._components[self.driver].go(self.duration)\n  File \"/home/csdms/wmt/permafrost/opt/pymt/pymt/component/component.py\", line 243, in go\n    self.initialize()\n  File \"/home/csdms/wmt/permafrost/opt/pymt/pymt/component/component.py\", line 256, in initialize\n    self._events.initialize()\n  File \"/home/csdms/wmt/permafrost/opt/pymt/pymt/events/manager.py\", line 114, in initialize\n    event.initialize()\n  File \"/home/csdms/wmt/permafrost/opt/pymt/pymt/events/port.py\", line 59, in initialize\n    self._port.initialize(*self._init_args)\n  File \"/home/csdms/wmt/permafrost/opt/pymt/pymt/framework/bmi_bridge.py\", line 292, in initialize\n    return bmi_call(self.bmi.initialize, *args)\n  File \"/home/csdms/wmt/permafrost/opt/pymt/pymt/framework/bmi_bridge.py\", line 49, in bmi_call\n    rtn = func(*args)\n_Exception\n", 
  "stage_dir": "/data/web/htdocs/wmt/api/permafrost/files/downloads/c18ac033-0fbb-457c-9401-39992117938a", 
  "id": 34, 
  "uuid": "c18ac033-0fbb-457c-9401-39992117938a"
}

**Comment by mdpiper** [comment]
Fixed! See the public model "KuModel Barrow series" in the **wmt-permafrost** instance. A link to download the output is [here](http://csdms.colorado.edu/pub/users/wmt/6f5a6c81-5669-486e-acf3-c7b88eb15e61.tar.gz).
