### ISSUE TITLE
testing Ku model 1D with scalar input

### ISSUE THREAD

**Issue by iovereem** [permamodel/permamodel#38]
I tested the Ku model 1 D with an arbitrary input for Barrow for 1 year: 
MAAT = -11.9
Amplitude of Temperature = 17.35
Snow Thickness =0.157

Model simulation runs and returns the active layer thickness accurately. 

But the other netcdf file for soil temperature reported soil temperature at -9999.9999

**Comment by mdpiper** [comment]
Fixed! See the public model "KuModel Barrow series" in the **wmt-permafrost** instance. A link to download the output is [here](http://csdms.colorado.edu/pub/users/wmt/6f5a6c81-5669-486e-acf3-c7b88eb15e61.tar.gz).
