### ISSUE TITLE
test Frost number 1D and Ku model 1D WMT implementation on PC

### ISSUE THREAD

**Issue by iovereem** [permamodel/permamodel#46]
Test whether these 2 WMT labs can be run and assignments completed through a PC environment.

just to note, I do not think of it as  pure ' permafrost model test', more as something useful for us to learn whether the workflow can be implemented in full on a PC.

 It may need a couple of simple things as figuring out how to unzip archives on a PC, see whether some browsers are flawed, that kind of stuff.

**Comment by wk1984** [comment]
I tested three notebook files of ku model, Ku_BR, Ku_FB, Ku_Single. All is working on PC. Although they are working well offline, I am not sure they could be suitable for WMT.

I am trying to create a notebook file to test frost number scalar (cfg file: 'Frostnumber_example_scalar.cfg'). Error msg is:
***
C:\Users\Kang\Desktop\permamodel\permamodel\components\frost_number.pyc in update(self)
    337             self.calculate_frost_numbers()
    338         else:
--> 339             raise ValueError("Year is past last year")
    340 
    341 if __name__ == "__main__":

ValueError: Year is past last year
***

**Comment by sc0tts** [comment]
@iovereem: Is this issue resolved with the recent repo updates?  I think it might be....

**Comment by iovereem** [comment]
yes, tested frost and ku both on PC. It needs downloads of winzip and panoply but all independent of our project.
