### ISSUE TITLE
cruAKtemp should use timestep of years

### ISSUE THREAD

**Issue by sc0tts** [permamodel/permamodel#50]
Instead of days, the timestep of cruAKtemp should be years.  The nominal day during those years is Dec 15th.  So for "year=1950", the date in the cruAKtemp model should be "12/15/1950", the current-month temperature field should be Dec 1950, the last 12 months should be Jan-Dec 1950, and the annual average field should be the average of the 12 monthly fields of Jan-Dec 1950.

**Comment by mdpiper** [comment]
Fixed with https://github.com/permamodel/cruAKtemp/pull/7.
