### ISSUE TITLE
KU model with timeseries

### ISSUE THREAD

**Issue by iovereem** [permamodel/permamodel#54]
I tested the Ku model with 3 uploaded files: MAAT, TAMP and SD for Fiarbanks for 55 years. 
It appears the model works fine if I run for 10 years, but not if i run for 55 years (or 54 years in case it was an loop miscount). 

This is the traceback: 
{
  "status": "error", 
  "model_id": 41, 
  "updated": "2017-05-17 12:15:15.974243", 
  "name": "KuModelFairbankOBSSNOW", 
  "created": "2017-05-17 12:15:07.736624", 
  "owner": "irina.overeem@gmail.com", 
  "message": "Traceback (most recent call last):\n  File \"/home/csdms/wmt/permafrost/opt/wmt-exe/wmtexe/cmd/slave.py\", line 53, in main\n    _ = slave.start_task(args.id, dir=args.exec_dir, env=env)\n  File \"/home/csdms/wmt/permafrost/opt/wmt-exe/wmtexe/slave.py\", line 78, in start_task\n    return self._tasks[id].execute()\n  File \"/home/csdms/wmt/permafrost/opt/wmt-exe/wmtexe/task.py\", line 652, in execute\n    self.run()\n  File \"/home/csdms/wmt/permafrost/opt/wmt-exe/wmtexe/task.py\", line 786, in run\n    model.go(filename='model.yaml')\n  File \"/home/csdms/wmt/permafrost/opt/pymt/pymt/component/model.py\", line 96, in go\n    self._components[self.driver].go(self.duration)\n  File \"/home/csdms/wmt/permafrost/opt/pymt/pymt/component/component.py\", line 247, in go\n    self.run(stop_time)\n  File \"/home/csdms/wmt/permafrost/opt/pymt/pymt/component/component.py\", line 268, in run\n    self._events.run(stop_time)\n  File \"/home/csdms/wmt/permafrost/opt/pymt/pymt/events/manager.py\", line 137, in run\n    event.run(self._timeline.time)\n  File \"/home/csdms/wmt/permafrost/opt/pymt/pymt/events/printer.py\", line 18, in run\n    self._printer.write()\n  File \"/home/csdms/wmt/permafrost/opt/pymt/pymt/portprinter/port_printer.py\", line 56, in write\n    self.resync_field_to_port()\n  File \"/home/csdms/wmt/permafrost/opt/pymt/pymt/portprinter/port_printer.py\", line 60, in resync_field_to_port\n    self._field = reconstruct_port_as_field(self._port, self._field)\n  File \"/home/csdms/wmt/permafrost/opt/pymt/pymt/portprinter/utils.py\", line 281, in reconstruct_port_as_field\n    data_array = port.get_value(var_name)\n  File \"/home/csdms/wmt/permafrost/opt/pymt/pymt/framework/bmi_bridge.py\", line 308, in get_value\n    dtype = self.get_var_type(name)\n  File \"/home/csdms/wmt/permafrost/opt/pymt/pymt/framework/bmi_bridge.py\", line 465, in get_var_type\n    return bmi_call(self.bmi.get_var_type, name)\n  File \"/home/csdms/wmt/permafrost/opt/pymt/pymt/framework/bmi_bridge.py\", line 49, in bmi_call\n    rtn = func(*args)\n_Exception\n", 
  "stage_dir": "/data/web/htdocs/wmt/api/permafrost/files/downloads/daea0c62-1bad-4070-9b30-6657675af30b", 
  "id": 64, 
  "uuid": "daea0c62-1bad-4070-9b30-6657675af30b"
}

**Comment by mdpiper** [comment]
@iovereem You may have to force-refresh (Command-Shift-R) your browser.

Afterward, I have the same setup in a public model, "KuModel Barrow series", which you can try for comparison.
