### ISSUE TITLE
Can't compare times in FrostnumberGeo BMI

### ISSUE THREAD

**Issue by mdpiper** [permamodel/permamodel#57]
In FrostnumberGeo, there's an error in comparing `datetime.date` objects with float times. Here's a (truncated) traceback:
```
Traceback (most recent call last):
  File "/home/mpiper/wmt/_testing/conda/lib/python2.7/site-packages/permamodel/components/bmi_frost_number_Geo.py", line 179, in update_until
    if stop_date < self._model._date_current:
TypeError: can't compare datetime.date to float
```

**Comment by mdpiper** [comment]
A little more information: the problem is with the `stop_date` value in the `update_until` method that comes from the babelized wrapper -- it's not a date, it's a number, like `1.0`.

**Comment by mdpiper** [comment]
I have what I think is a solution for this issue and https://github.com/permamodel/cruAKtemp/issues/10. I'll submit PRs.

**Comment by sc0tts** [comment]
Sounds good.  I am looking at it too.  Either the loop condition needs to
use bmi's get_current_time() or get_end_time(),
...or the stop_date variable needs to be converted to a datetime.date.

**Comment by sc0tts** [comment]
I was thinking something like:
`    def update_until(self, stop_date):

        # Ensure that stop_year is at least the current year

        #if stop_date < self._model._date_current:

        if stop_date < self.get_current_time():`
around line 180 of bmi_frost_number_Geo.py.

And then similarly a few lines below...use self.get_current_time() instead of self._model._date_current.
